### ISSUE TITLE
Onder de plak!

### ISSUE THREAD

**Issue by ThoompyEagle** [LuudJanssen/amy-21-diner-landing#1]
Prachtig gebeund hoor Loeder, maar jezus man wat zit jij onder de plak! 😜 

Gr.
Een conjo die echt niet onder de plak zit hoor, waar heb je het over?!

**Comment by ThjSmits** [comment]
Ik ben hier voor de easter eggs, waar kan ik die vinden?

**Comment by LuudJanssen** [comment]
@ThoompyEagle Euh, als een vriend zelf besluit om iets leuks te maken voor z'n vriendin, zit hij dan per definitie ook onder de plak?

_HELP ME, ALSJEBLIEFT, AAAHH_

@ThjSmits [hier](https://github.com/LuudJanssen/amy-21-diner-landing/blob/main/data/page-option.enum.ts)
